### ISSUE TITLE
Octave port?

### ISSUE THREAD

**Issue by sdwfrost** [shaman-lab/COVID-19Projection#1]
Hi @shaman-lab 

Nice work on this! I was wondering whether you'd consider a port to Octave? The model_eakf MEX file seems to compile happily, but Octave lacks a table class, so it would require some backporting on the data input. Not great for performance, but it would open up the model to those without a Matlab license.

**Comment by tkcy** [comment]
It's a great idea but we just don't have the bandwidth for this - sorry!
