### ISSUE TITLE
I don't understand what the different file names represent

### ISSUE THREAD

**Issue by thehammah** [shaman-lab/COVID-19Projection#2]
I looked a thttps://github.com/shaman-lab/COVID-19Projection/blob/master/README.md. 

You say that the file names
_Projections for daily new confirmed case and daily new infection are reported in Projection_nointerv.csv, Projection_80contact.csv, Projection_70contact.csv and Projection_60contact.csv

Projections for cumulative demand of hospital beds, ICU, ventilators and daily mortality are reported in bed_nointerv.csv, bed_80contact.csv, bed_70contact and bed_60contact.csv._

Yet when I download I see file names:
Projection_80, Projection_80w, etc. 

I do not see any files with _60 or _20

furthermore I do not see any definition of what say 80w5, 80w10, 80x5, or 80x10 mean?  Is there some other table or definition page I can look at?

**Comment by tkcy** [comment]
@thehammah  The Readme file has been updated to reflect the new filenames.  Thanks!
