### ISSUE TITLE
Projections for daily new confirmed case and daily new infection are reported in Projection_*.csv

### ISSUE THREAD

**Issue by thehammah** [shaman-lab/COVID-19Projection#5]
I only see one set of numbers in each file.  IE there are no separate columns that might indicate what is confirmed cases vs new infections.   Is this distinguished by file name?   I think all the projection_ files currently just have projected case information but just wanted to confirm

**Comment by tkcy** [comment]
Which files are you looking at?

Projection files have the following columns:
`county,fips,Date,report_2.5,report_25,report_50,report_75,report_97.5,total_2.5,total_25,total_50,total_75,total_97.5`

report indicates new confirmed (reported) cases, total is new infections (reported and unreported).

**Comment by thehammah** [comment]
ok thank you!  I understand now.
