### ISSUE TITLE
With file name changes recently in Project run folders, will the "Low, Mid, High". model name be available permanently?

### ISSUE THREAD

**Issue by thehammah** [shaman-lab/COVID-19Projection#7]
We originally mapped to the files in the model run date folders, but noticed that as you changed your assumptions the files name also changed.   We are trying to automate the data load and noticed in the Latest projections folder you have a low file a mid file and a high file.  If these three files are permanent we can use these instead.

thanks!

**Comment by tkcy** [comment]
@thehammah  Yes, the Latest Projections folder will now have permanent high/mid/low file names.  We'll try to keep the metadata updated as to which specific scenario each of these refer to (eg. 80contact, season4 etc.).
